var data = `
{
  "schoolResults": {
    "private": [
    {
      "distanceStr": "0.98 mi",
      "schoolid": "259999943899",
      "schoolName": "Tara Montessori School",
      "phone": "(978) 526-8487",
      "url": "https://www.schooldigger.com/go/MA/schools/9999943899/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/9999943899/search.aspx",
      "address": {
        "street": "62 School St",
        "city": "Manchester By The Sea",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01944"
      },
      "addressFull": "62 School St Manchester By The Sea, MA 01944",
      "distance": "0.98",
      "lowGrade": "PK",
      "highGrade": "KG",
      "schoolLevel": "Private",
      "isCharterSchool": "(n/a)",
      "isMagnetSchool": "(n/a)",
      "isVirtualSchool": "(n/a)",
      "isTitleISchool": "(n/a)",
      "isTitleISchoolwideSchool": "(n/a)",
      "district": {
        "districtID": "2599999",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2018",
        "numberOfStudents": "11",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "1",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "1",
        "pupilTeacherRatio": "11",
        "numberofAfricanAmericanStudents": "0",
        "numberofAsianStudents": "0",
        "numberofHispanicStudents": "0",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "11",
        "numberofTwoOrMoreRaceStudents": "0",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": true,
      "privateDays": "140",
      "privateHours": "7.5",
      "privateHasLibrary": "false",
      "privateCoed": "Coed",
      "privateOrientation": "Nonsectarian",
      "hasBoundary": "false",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }, {
      "distanceStr": "1.49 mi",
      "schoolid": "259999949816",
      "schoolName": "Landmark School - Elementary Middle School",
      "phone": "(978) 236-3100",
      "url": "https://www.schooldigger.com/go/MA/schools/9999949816/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/9999949816/search.aspx",
      "address": {
        "street": "PO Box 1489 167 Bridge St",
        "city": "Manchester",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01944"
      },
      "addressFull": "PO Box 1489 167 Bridge St Manchester, MA 01944",
      "distance": "1.49",
      "lowGrade": "02",
      "highGrade": "08",
      "schoolLevel": "Private",
      "isCharterSchool": "(n/a)",
      "isMagnetSchool": "(n/a)",
      "isVirtualSchool": "(n/a)",
      "isTitleISchool": "(n/a)",
      "isTitleISchoolwideSchool": "(n/a)",
      "district": {
        "districtID": "2599999",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2018",
        "numberOfStudents": "165",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "55",
        "pupilTeacherRatio": "3",
        "numberofAfricanAmericanStudents": "2",
        "numberofAsianStudents": "2",
        "numberofHispanicStudents": "4",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "157",
        "numberofTwoOrMoreRaceStudents": "0",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": true,
      "privateDays": "180",
      "privateHours": "7.25",
      "privateHasLibrary": "true",
      "privateCoed": "Coed",
      "privateOrientation": "Nonsectarian",
      "hasBoundary": "false",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }, {
      "distanceStr": "1.60 mi",
      "schoolid": "259999927286",
      "schoolName": "Brookwood School",
      "phone": "(978) 526-4500",
      "url": "https://www.schooldigger.com/go/MA/schools/9999927286/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/9999927286/search.aspx",
      "address": {
        "street": "1 Brookwood Rd",
        "city": "Manchester",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01944"
      },
      "addressFull": "1 Brookwood Rd Manchester, MA 01944",
      "distance": "1.60",
      "lowGrade": "PK",
      "highGrade": "08",
      "schoolLevel": "Private",
      "isCharterSchool": "(n/a)",
      "isMagnetSchool": "(n/a)",
      "isVirtualSchool": "(n/a)",
      "isTitleISchool": "(n/a)",
      "isTitleISchoolwideSchool": "(n/a)",
      "district": {
        "districtID": "2599999",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2018",
        "numberOfStudents": "388",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "65",
        "pupilTeacherRatio": "6",
        "numberofAfricanAmericanStudents": "11",
        "numberofAsianStudents": "15",
        "numberofHispanicStudents": "13",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "340",
        "numberofTwoOrMoreRaceStudents": "9",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": true,
      "privateDays": "166",
      "privateHours": "7.8333333333",
      "privateHasLibrary": "true",
      "privateCoed": "Coed",
      "privateOrientation": "Nonsectarian",
      "hasBoundary": "false",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }, {
      "distanceStr": "2.59 mi",
      "schoolid": "259999927422",
      "schoolName": "Glen Urquhart School",
      "phone": "(978) 927-1064",
      "url": "https://www.schooldigger.com/go/MA/schools/9999927422/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/9999927422/search.aspx",
      "address": {
        "street": "74 Hart St",
        "city": "Beverly",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01915"
      },
      "addressFull": "74 Hart St Beverly, MA 01915",
      "distance": "2.59",
      "lowGrade": "KG",
      "highGrade": "08",
      "schoolLevel": "Private",
      "isCharterSchool": "(n/a)",
      "isMagnetSchool": "(n/a)",
      "isVirtualSchool": "(n/a)",
      "isTitleISchool": "(n/a)",
      "isTitleISchoolwideSchool": "(n/a)",
      "district": {
        "districtID": "2599999",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2018",
        "numberOfStudents": "181",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "30",
        "pupilTeacherRatio": "6",
        "numberofAfricanAmericanStudents": "3",
        "numberofAsianStudents": "8",
        "numberofHispanicStudents": "4",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "159",
        "numberofTwoOrMoreRaceStudents": "7",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": true,
      "privateDays": "167",
      "privateHours": "7.0",
      "privateHasLibrary": "true",
      "privateCoed": "Coed",
      "privateOrientation": "Nonsectarian",
      "hasBoundary": "false",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }, {
      "distanceStr": "3.58 mi",
      "schoolid": "259999927531",
      "schoolName": "Landmark School",
      "phone": "(978) 236-3010",
      "url": "https://www.schooldigger.com/go/MA/schools/9999927531/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/9999927531/search.aspx",
      "address": {
        "street": "PO Box 227",
        "city": "Prides Crossing",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01965"
      },
      "addressFull": "PO Box 227 Prides Crossing, MA 01965",
      "distance": "3.58",
      "lowGrade": "02",
      "highGrade": "08",
      "schoolLevel": "Private",
      "isCharterSchool": "(n/a)",
      "isMagnetSchool": "(n/a)",
      "isVirtualSchool": "(n/a)",
      "isTitleISchool": "(n/a)",
      "isTitleISchoolwideSchool": "(n/a)",
      "district": {
        "districtID": "2599999",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2018",
        "numberOfStudents": "165",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "55",
        "pupilTeacherRatio": "3",
        "numberofAfricanAmericanStudents": "3",
        "numberofAsianStudents": "4",
        "numberofHispanicStudents": "3",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "155",
        "numberofTwoOrMoreRaceStudents": "0",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": true,
      "privateDays": "180",
      "privateHours": "7.2166666667",
      "privateHasLibrary": "true",
      "privateCoed": "Coed",
      "privateOrientation": "Nonsectarian",
      "hasBoundary": "false",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }, {
      "distanceStr": "4.09 mi",
      "schoolid": "259999927990",
      "schoolName": "Waring School",
      "phone": "(978) 927-8793",
      "url": "https://www.schooldigger.com/go/MA/schools/9999927990/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/9999927990/search.aspx",
      "address": {
        "street": "35 Standley St",
        "city": "Beverly",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01915"
      },
      "addressFull": "35 Standley St Beverly, MA 01915",
      "distance": "4.09",
      "lowGrade": "06",
      "highGrade": "12",
      "schoolLevel": "Private",
      "isCharterSchool": "(n/a)",
      "isMagnetSchool": "(n/a)",
      "isVirtualSchool": "(n/a)",
      "isTitleISchool": "(n/a)",
      "isTitleISchoolwideSchool": "(n/a)",
      "district": {
        "districtID": "2599999",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2018",
        "numberOfStudents": "165",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "24",
        "pupilTeacherRatio": "7",
        "numberofAfricanAmericanStudents": "5",
        "numberofAsianStudents": "11",
        "numberofHispanicStudents": "5",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "133",
        "numberofTwoOrMoreRaceStudents": "11",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": true,
      "privateDays": "175",
      "privateHours": "9.0",
      "privateHasLibrary": "true",
      "privateCoed": "Coed",
      "privateOrientation": "Nonsectarian",
      "hasBoundary": "false",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }, {
      "distanceStr": "4.53 mi",
      "schoolid": "259999952516",
      "schoolName": "The Academy At Penguin Hall",
      "phone": "(978) 468-6200",
      "url": "https://www.schooldigger.com/go/MA/schools/9999952516/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/9999952516/search.aspx",
      "address": {
        "street": "36 Essex St",
        "city": "Wenham",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01984"
      },
      "addressFull": "36 Essex St Wenham, MA 01984",
      "distance": "4.53",
      "lowGrade": "09",
      "highGrade": "12",
      "schoolLevel": "Private",
      "isCharterSchool": "(n/a)",
      "isMagnetSchool": "(n/a)",
      "isVirtualSchool": "(n/a)",
      "isTitleISchool": "(n/a)",
      "isTitleISchoolwideSchool": "(n/a)",
      "district": {
        "districtID": "2599999",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2018",
        "numberOfStudents": "97",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "16",
        "pupilTeacherRatio": "6",
        "numberofAfricanAmericanStudents": "1",
        "numberofAsianStudents": "4",
        "numberofHispanicStudents": "3",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "85",
        "numberofTwoOrMoreRaceStudents": "4",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": true,
      "privateDays": "175",
      "privateHours": "7.5",
      "privateHasLibrary": "false",
      "privateCoed": "Female",
      "privateOrientation": "Nonsectarian",
      "hasBoundary": "false",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }],
    "public": [
    {
      "distanceStr": "0.95 mi",
      "schoolid": "250006701110",
      "schoolName": "Manchester Memorial Elementary",
      "phone": "(978) 526-1908",
      "url": "https://www.schooldigger.com/go/MA/schools/0006701110/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/0006701110/search.aspx",
      "address": {
        "street": "43 Lincoln Street",
        "city": "Manchester",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01944"
      },
      "addressFull": "43 Lincoln Street Manchester, MA 01944",
      "distance": "0.95",
      "lowGrade": "PK",
      "highGrade": "05",
      "schoolLevel": "Elementary",
      "isCharterSchool": "No",
      "isMagnetSchool": "No",
      "isVirtualSchool": "No",
      "isTitleISchool": "No",
      "isTitleISchoolwideSchool": "No",
      "district": {
        "districtID": "2500067",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [{
        "year": "2021",
        "rank": "28",
        "rankOf": "935",
        "rankStars": "5",
        "rankLevel": "Elementary",
        "rankStatewidePercentage": null,
        "averageStandardScore": null
      }, {
        "year": "2019",
        "rank": "107",
        "rankOf": "942",
        "rankStars": "4",
        "rankLevel": "Elementary",
        "rankStatewidePercentage": null,
        "averageStandardScore": null
      }],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2020",
        "numberOfStudents": "311",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "35",
        "pupilTeacherRatio": "9",
        "numberofAfricanAmericanStudents": "5",
        "numberofAsianStudents": "1",
        "numberofHispanicStudents": "3",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "299",
        "numberofTwoOrMoreRaceStudents": "3",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": false,
      "privateDays": null,
      "privateHours": null,
      "privateHasLibrary": null,
      "privateCoed": null,
      "privateOrientation": null,
      "hasBoundary": "true",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }, {
      "distanceStr": "1.15 mi",
      "schoolid": "250006702653",
      "schoolName": "Manchester Essex Regional Middle School",
      "phone": "(978) 526-2022",
      "url": "https://www.schooldigger.com/go/MA/schools/0006702653/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/0006702653/search.aspx",
      "address": {
        "street": "36 Lincoln Street",
        "city": "Manchester",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01944"
      },
      "addressFull": "36 Lincoln Street Manchester, MA 01944",
      "distance": "1.15",
      "lowGrade": "06",
      "highGrade": "08",
      "schoolLevel": "Middle",
      "isCharterSchool": "No",
      "isMagnetSchool": "No",
      "isVirtualSchool": "No",
      "isTitleISchool": "Yes",
      "isTitleISchoolwideSchool": "No",
      "district": {
        "districtID": "2500067",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [{
        "year": "2021",
        "rank": "94",
        "rankOf": "497",
        "rankStars": "4",
        "rankLevel": "Middle",
        "rankStatewidePercentage": null,
        "averageStandardScore": null
      }, {
        "year": "2019",
        "rank": "117",
        "rankOf": "498",
        "rankStars": "4",
        "rankLevel": "Middle",
        "rankStatewidePercentage": null,
        "averageStandardScore": null
      }],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2020",
        "numberOfStudents": "357",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "32",
        "pupilTeacherRatio": "11",
        "numberofAfricanAmericanStudents": "0",
        "numberofAsianStudents": "3",
        "numberofHispanicStudents": "3",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "347",
        "numberofTwoOrMoreRaceStudents": "4",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": false,
      "privateDays": null,
      "privateHours": null,
      "privateHasLibrary": null,
      "privateCoed": null,
      "privateOrientation": null,
      "hasBoundary": "true",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }, {
      "distanceStr": "1.15 mi",
      "schoolid": "250006701109",
      "schoolName": "Manchester Essex Regional High School",
      "phone": "(978) 526-4412",
      "url": "https://www.schooldigger.com/go/MA/schools/0006701109/school.aspx",
      "urlCompare": "https://www.schooldigger.com/go/MA/schools/0006701109/search.aspx",
      "address": {
        "street": "36 Lincoln Street",
        "city": "Manchester",
        "state": "MA",
        "stateFull": "Massachusetts",
        "zip": "01944"
      },
      "addressFull": "36 Lincoln Street Manchester, MA 01944",
      "distance": "1.15",
      "lowGrade": "09",
      "highGrade": "12",
      "schoolLevel": "High",
      "isCharterSchool": "No",
      "isMagnetSchool": "No",
      "isVirtualSchool": "No",
      "isTitleISchool": "No",
      "isTitleISchoolwideSchool": "No",
      "district": {
        "districtID": "2500067",
        "districtName": null,
        "url": "https://www.schooldigger.com/go/MA/district//search.aspx",
        "rankURL": "https://www.schooldigger.com/go/MA/districtrank.aspx?finddistrict="
      },
      "county": {
        "countyName": "Essex County",
        "countyURL": "https://www.schooldigger.com/go/MA/county/Essex+County/serach.aspx"
      },
      "rankHistory": [{
        "year": "2021",
        "rank": "43",
        "rankOf": "282",
        "rankStars": "4",
        "rankLevel": "High",
        "rankStatewidePercentage": null,
        "averageStandardScore": null
      }, {
        "year": "2019",
        "rank": "33",
        "rankOf": "351",
        "rankStars": "5",
        "rankLevel": "High",
        "rankStatewidePercentage": null,
        "averageStandardScore": null
      }],
      "rankMovement": null,
      "locationIsWithinBoundary": null,
      "schoolYearlyDetails": [{
        "year": "2020",
        "numberOfStudents": "483",
        "percentFreeDiscLunch": null,
        "percentofAfricanAmericanStudents": "0",
        "percentofAsianStudents": "0",
        "percentofHispanicStudents": "0",
        "percentofIndianStudents": "0",
        "percentofPacificIslanderStudents": "0",
        "percentofWhiteStudents": "0",
        "percentofTwoOrMoreRaceStudents": "0",
        "percentofUnspecifiedRaceStudents": "0",
        "teachersFulltime": "44",
        "pupilTeacherRatio": "11",
        "numberofAfricanAmericanStudents": "0",
        "numberofAsianStudents": "7",
        "numberofHispanicStudents": "7",
        "numberofIndianStudents": "0",
        "numberofPacificIslanderStudents": "0",
        "numberofWhiteStudents": "466",
        "numberofTwoOrMoreRaceStudents": "3",
        "numberofUnspecifiedRaceStudents": "0"
      }],
      "isPrivate": false,
      "privateDays": null,
      "privateHours": null,
      "privateHasLibrary": null,
      "privateCoed": null,
      "privateOrientation": null,
      "hasBoundary": "true",
      "expenditurePerStudent": null,
      "gifted&talented": null,
      "dualEnrollment": null,
      "creditRecovery": null,
      "singleSexClasses": null,
      "apCourse": null,
      "internationalBaccalaureate": null,
      "corporalPunishment": null,
      "interscholarAthletics": null,
      "offersKingergarten": null,
      "offersFullDayKingergarten": null,
      "apEnrollment": null,
      "expendituresPerStudentStr": "$0"
    }]
  },
  "citation": "Based on Education Office for Civil Right's Civil Rights Data Collection and National Center for Education Statistics"
}
`;

export function getSchoolData() {
  return JSON.parse(data);
}